name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: cd
      run: cd src/
    - name: pwd
      run: pwd
    - name: make
      run: make install WITH_WGQUICK=yes PREFIX=/usr/local/
